language: scala

jdk: oraclejdk8

dist: trusty

scala:
   - 2.12.8

script:
    - docker build --tag $(basename $PWD) --file dockerfile . && docker run --entrypoint '' -it $(basename $PWD) make test

after_success:
  - export CODECOV_TOKEN="15bf6b07-622f-48d8-b746-e001b5fc8e73"
  - bash <(curl -s https://codecov.io/bash)
