language: scala

jdk: oraclejdk8

dist: trusty

scala:
   - 2.12.8

script:
    - make docker_build docker_test

after_success:
  - export CODECOV_TOKEN="15bf6b07-622f-48d8-b746-e001b5fc8e73"
  - bash <(curl -s https://codecov.io/bash)

# vim: set filetype=yaml fileformat=unix nowrap spell spelllang=en:
