language: scala

jdk: oraclejdk8

dist: trusty

scala:
   - 2.12.8

before_install:
    - cd $(mktemp -d) && git clone --depth 1 --branch dev https://github.com/fmv1992/scala_cli_parser && cd ./scala_cli_parser && make publishlocal

script:
    - make

after_success:
  - export CODECOV_TOKEN="15bf6b07-622f-48d8-b746-e001b5fc8e73"
  - bash <(curl -s https://codecov.io/bash)

# vim: set filetype=yaml fileformat=unix nowrap spell spelllang=en:
